### ISSUE TITLE
Add support for node 20.9.0

### ISSUE THREAD

**Issue by neudysrd** [kmertozen/strapi-cdn-prefix#5]
I would like you to add support for newer versions of node, when installing I get the following error:

error strapi-plugin-cdn-prefix@1.0.3: The engine "node" is incompatible with this module. Expected version ">=14.19.1 <=18.x.x". Got "20.9.0"
error Found incompatible module.

**Comment by kmertozen** [comment]
done, you can use it with node 20.x.x

**Comment by neudysrd** [comment]
Confirmed. Work!
