### ISSUE TITLE
Lack of information in the documentation

### ISSUE THREAD

**Issue by neudysrd** [kmertozen/strapi-cdn-prefix#6]
I recently installed the strapi-cdn-prefix plugin, I was able to install it quickly without any problems and indeed, all media files have had their URLs customized.

However, I have the following concerns that I understand should be in the documentation for clarity.

1. Should my subdomain (example cdn.example.com) point to the same IP as the Strapi app server?
2. Should I make any additional configuration in Strapi so that the image URLs are resolved once they are publicly consulted?

**Comment by kmertozen** [comment]
1. No, there is no need.

2. If the plugin is correctly configured to prepend the CDN URL to the media files, no additional configuration in Strapi is needed. The plugin should handle generating the correct URLs. However, ensure that the CDN is properly set up to serve these files from the correct origin.

This plugin only adds a CDN prefix to image URLs in API or GraphQL requests, nothing more.
