### ISSUE TITLE
The JSX syntax extension is not currently enabled

### ISSUE THREAD

**Issue by neudysrd** [kmertozen/strapi-cdn-prefix#7]
After updating to version 5 of Strapi, and running the project I am getting the error:

`✘ [ERROR] The JSX syntax extension is not currently enabled

    node_modules/strapi-plugin-cdn-prefix/admin/src/components/PluginIcon/index.js:10:25:
      10 │ const PluginIcon = () => <Puzzle />;
         ╵                          ^

  The esbuild loader for this file is currently set to "js" but it must be set to "jsx" to be able
  to parse JSX syntax. You can use "loader: { '.js': 'jsx' }" to do that.

✘ [ERROR] The JSX syntax extension is not currently enabled

    node_modules/strapi-plugin-cdn-prefix/admin/src/pages/App/index.js:16:4:
      16 │     <div>
         ╵     ^

  The esbuild loader for this file is currently set to "js" but it must be set to "jsx" to be able
  to parse JSX syntax. You can use "loader: { '.js': 'jsx' }" to do that.

✘ [ERROR] The JSX syntax extension is not currently enabled

    node_modules/strapi-plugin-cdn-prefix/admin/src/pages/HomePage/index.js:13:4:
      13 │     <div>
         ╵     ^

  The esbuild loader for this file is currently set to "js" but it must be set to "jsx" to be able
  to parse JSX syntax. You can use "loader: { '.js': 'jsx' }" to do that.

17:42:59 [vite] error while updating dependencies:
Error: Build failed with 3 errors:
node_modules/strapi-plugin-cdn-prefix/admin/src/components/PluginIcon/index.js:10:25: ERROR: The JSX syntax extension is not currently enabled
node_modules/strapi-plugin-cdn-prefix/admin/src/pages/App/index.js:16:4: ERROR: The JSX syntax extension is not currently enabled
node_modules/strapi-plugin-cdn-prefix/admin/src/pages/HomePage/index.js:13:4: ERROR: The JSX syntax extension is not currently enabled
    at failureErrorWithLog (C:\Users\neudy\Documents\dev\anton\strapi-cms\node_modules\vite\node_modules\esbuild\lib\main.js:1651:15)
    at C:\Users\neudy\Documents\dev\anton\strapi-cms\node_modules\vite\node_modules\esbuild\lib\main.js:1059:25
    at C:\Users\neudy\Documents\dev\anton\strapi-cms\node_modules\vite\node_modules\esbuild\lib\main.js:1527:9
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)`

**Comment by kmertozen** [comment]
Sorry, this plugin currently does not support Strapi v5

**Comment by neudysrd** [comment]
What is the TEA for the upgrade?
